export const Products: ProductCardProps[] = [
  {
    id: "1",
    title: "Quantify",
    tag: "New",
    image: "/assets/images/product_image.png",
    description: "AI-driven insights into consumer behavior.",
  },
  {
    id: "2",
    title: "Webify",
    tag: "New",
    image: "/assets/images/p_2.png",
    description: "Revolutionizing web development with simplicity.",
  },
  {
    id: "3",
    title: "Supportify",
    tag: "Highlight",
    image: "/assets/images/p_3.png",
    description: "Redefining customer support with AI for your excellence.",
  },
  {
    id: "4",
    title: "Quantify",
    tag: "New",
    image: "/assets/images/product_image.png",
    description: "AI-driven insights into consumer behavior.",
  },
  {
    id: "5",
    title: "Webify",
    tag: "New",
    image: "/assets/images/p_2.png",
    description: "Revolutionizing web development with simplicity.",
  },
  {
    id: "6",
    title: "Supportify",
    tag: "Highlight",
    image: "/assets/images/p_3.png",
    description: "Redefining customer support with AI for your excellence.",
  },
  {
    id: "7",
    title: "Quantify",
    tag: "New",
    image: "/assets/images/product_image.png",
    description: "AI-driven insights into consumer behavior.",
  },
  {
    id: "8",
    title: "Webify",
    tag: "New",
    image: "/assets/images/p_2.png",
    description: "Revolutionizing web development with simplicity.",
  },
  {
    id: "9",
    title: "Supportify",
    tag: "Highlight",
    image: "/assets/images/p_3.png",
    description: "Redefining customer support with AI for your excellence.",
  },
];
