export const Products: ProductCardProps[] = [
  {
    id: "1",
    title: "Quantify",
    tag: "New",
    category: "ai",
    image: "/assets/images/product_image.png",
    description: "AI-driven insights into consumer behavior.",
  },
  {
    id: "2",
    title: "Webify",
    tag: "",
    category: "analytics",
    image: "/assets/images/p_2.png",
    description: "Revolutionizing web development with simplicity.",
  },
  {
    id: "3",
    title: "Supportify",
    tag: "Highlight",
    category: "ai",
    image: "/assets/images/p_3.png",
    description: "Redefining customer support with AI for your excellence.",
  },
  {
    id: "4",
    title: "Strategize",
    tag: "",
    category: "ai",
    image: "/assets/images/p_4.png",
    description: "Your virtual CFO for financial strategies made with ChatGPT.",
  },
  {
    id: "5",
    title: "Innovate",
    tag: "Sponsored",
    category: "admin",
    image: "/assets/images/p_5.png",
    description: "Turn ideas into successful products seamlessly.",
  },
  {
    id: "6",
    title: "Optimize",
    tag: "",
    category: "analytics",
    image: "/assets/images/p_6.png",
    description: "Efficiency solutions for modern manufacturing.",
  },
  {
    id: "7",
    title: "Propertify",
    tag: "New",
    category: "api",
    image: "/assets/images/p_7.png",
    description: "Smart real estate management and analytics.",
  },
  {
    id: "8",
    title: "Marketify",
    tag: "",
    category: "bug",
    image: "/assets/images/p_8.png",
    description: "Navigate market trends with confidence.",
  },
  {
    id: "9",
    title: "Techify",
    tag: "Sponsored",
    category: "business",
    image: "/assets/images/p_9.png",
    description: "Cutting-edge tech services for enterprise needs.",
  },
  {
    id: "10",
    title: "Code Craft",
    tag: "",
    category: "business",
    image: "/assets/images/p_10.png",
    description:
      "Streamlined web design platform for responsive, modern websites",
  },
  {
    id: "11",
    title: "Scoope",
    tag: "",
    category: "admin",
    image: "/assets/images/p_11.png",
    description:
      "Simplifying complex data analysis with intuitive visualization tools.",
  },
  {
    id: "12",
    title: "Connectify",
    tag: "",
    category: "web-tools",
    image: "/assets/images/p_12.png",
    description:
      "Enhance your customer support with our integrated service suite.",
  },
  {
    id: "13",
    title: "Curatify",
    tag: "",
    category: "finance",
    image: "/assets/images/p_13.png",
    description: "Your virtual CFO for financial strategies made with ChatGPT.",
  },
  {
    id: "14",
    title: "Venture Vault",
    tag: "Sponsored",
    category: "web-tools",
    image: "/assets/images/p_14.png",
    description: "Secure business planning and strategic management software.",
  },
  {
    id: "15",
    title: "Launch Pad",
    tag: "",
    category: "services",
    image: "/assets/images/p_15.png",
    description:
      "All-in-one toolkit for entrepreneurs to kickstart their business journey.",
  },
];
